---
language: perl

perl:
  - "5.14"
  - "5.24"

services:
  - docker

install: cpanm -n App::cpm; cpm install -g Module::Install inc::Module::Install; for MOD in Whatbot*/; do echo $MOD; cd $MOD; PERL5LIB=../Whatbot/lib perl Makefile.PL; mymeta-cpanfile > cpanfile; cpm install -g --cpanfile=cpanfile; cd ..; done
script: "A=0; export PERL5LIB=$(find `pwd` -name lib | tr '\n' ':').; for MOD in Whatbot*/; do echo $MOD; cd $MOD; perl -Ilib Makefile.PL && make && if [ -e t ]; then prove -Ilib t; if [ $? -ne 0 ]; then A=$?; break; fi; fi; cpanm --notest .; cd ..; done; exit $A"
