---
language: perl
perl:
  - "5.14"
  - "5.20"
  - "5.24"
install: cpanm --quiet Module::Install inc::Module::Install; for MOD in Whatbot*/; do echo $MOD; cd $MOD; PERL5LIB=../Whatbot/lib cpanm --quiet --installdeps --notest .; cd ..; done
script: "A=0; for MOD in Whatbot*/; do echo $MOD; cd $MOD; PERL5LIB=../Whatbot/lib perl Makefile.PL && make && if [ -e t ]; then prove -Ilib t; if [ $? -ne 0 ]; then A=$?; break; fi; fi; cpanm --notest .; cd ..; done; exit $A"
